### ISSUE TITLE
GTFS-rt tripIds don't match static GTFS

### ISSUE THREAD

**Issue by juanborre** [whatcomtrans/transitdata#7]
Hi,

The GTFS-rt seems to be out of sync with the GTFS data. The tripIds don't match.

For example, I see tripIds 49090 and 1288090 but they are not in the GTFS at: https://github.com/whatcomtrans/publicwtadata/blob/master/GTFS/wta_gtfs_latest.zip%E2%80%8B%E2%80%8B

Could you take a look at it?

Thanks in advance

**Comment by danielm-ridewta** [comment]
Sorry about that. There was an issue with the static feed matching up with the realtime feed on our end. I've pushed a new static feed that should match up better now.

**Comment by juanborre** [comment]
Thanks. This has fixed the issue 🙏
